version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
      XPACK_GRAPH_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_WATCHER_ENABLED: "false"
      ELASTICSEARCH_URL: "http://es:9200"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:es"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.1
    command: -f /usr/share/logstash/config/pipeline.conf
    volumes:
      - ./pipeline.conf:/usr/share/logstash/config/pipeline.conf
    environment:
      xpack.monitoring.enabled: "false"
    links:
      - "elasticsearch:es"

  filebeat:
    build: filebeat/
    links:
      - "logstash:lg"
      - "elasticsearch:es"

volumes:
  esdata:

